//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Externo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:servicios", ConfigurationName="ServiceReference1.serviciosPortType")]
    public interface serviciosPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#HelloWorld", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#Saludar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string Saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#Saludar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> SaludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string GuardarLog(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarLog", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GuardarLogAsync(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#Sumar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int Sumar(int numero_1, int numero_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#Sumar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> SumarAsync(int numero_1, int numero_2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerFrutas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string[] ObtenerFrutas();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerFrutas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string[]> ObtenerFrutasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarFrutas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string GuardarFrutas(string[] frutas);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarFrutas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GuardarFrutasAsync(string[] frutas);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerEquipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Externo.ServiceReference1.Equipos[] ObtenerEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerEquipos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Externo.ServiceReference1.Equipos[]> ObtenerEquiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarEquipos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string GuardarEquipos(Externo.ServiceReference1.Equipos[] equipos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarEquipos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GuardarEquiposAsync(Externo.ServiceReference1.Equipos[] equipos);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string GuardarXML(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarXML", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GuardarXMLAsync(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#RetornarJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string RetornarJson();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#RetornarJson", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> RetornarJsonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarJson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string GuardarJson(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarJson", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> GuardarJsonAsync(string json);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerProductos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ObtenerProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerProductos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ObtenerProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Externo.ServiceReference1.Producto ObtenerProducto(int idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerProducto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Externo.ServiceReference1.Producto> ObtenerProductoAsync(int idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ActualizarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ActualizarProducto(Externo.ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ActualizarProducto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ActualizarProductoAsync(Externo.ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int GuardarProducto(Externo.ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#GuardarProducto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> GuardarProductoAsync(Externo.ServiceReference1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#EliminarProducto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string EliminarProducto(int idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#EliminarProducto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> EliminarProductoAsync(int idproducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerFecha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ObtenerFecha();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerFecha", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ObtenerFechaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerHora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Equipos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string ObtenerHora();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:servicios#ObtenerHora", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> ObtenerHoraAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicios")]
    public partial class Equipos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string paisField;
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:servicios")]
    public partial class Producto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idproductoField;
        
        private string nombreField;
        
        private double precioField;
        
        private int stockField;
        
        /// <remarks/>
        public int idproducto {
            get {
                return this.idproductoField;
            }
            set {
                this.idproductoField = value;
                this.RaisePropertyChanged("idproducto");
            }
        }
        
        /// <remarks/>
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface serviciosPortTypeChannel : Externo.ServiceReference1.serviciosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class serviciosPortTypeClient : System.ServiceModel.ClientBase<Externo.ServiceReference1.serviciosPortType>, Externo.ServiceReference1.serviciosPortType {
        
        public serviciosPortTypeClient() {
        }
        
        public serviciosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public serviciosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public serviciosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public string Saludar(string nombre) {
            return base.Channel.Saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string nombre) {
            return base.Channel.SaludarAsync(nombre);
        }
        
        public string GuardarLog(string mensaje) {
            return base.Channel.GuardarLog(mensaje);
        }
        
        public System.Threading.Tasks.Task<string> GuardarLogAsync(string mensaje) {
            return base.Channel.GuardarLogAsync(mensaje);
        }
        
        public int Sumar(int numero_1, int numero_2) {
            return base.Channel.Sumar(numero_1, numero_2);
        }
        
        public System.Threading.Tasks.Task<int> SumarAsync(int numero_1, int numero_2) {
            return base.Channel.SumarAsync(numero_1, numero_2);
        }
        
        public string[] ObtenerFrutas() {
            return base.Channel.ObtenerFrutas();
        }
        
        public System.Threading.Tasks.Task<string[]> ObtenerFrutasAsync() {
            return base.Channel.ObtenerFrutasAsync();
        }
        
        public string GuardarFrutas(string[] frutas) {
            return base.Channel.GuardarFrutas(frutas);
        }
        
        public System.Threading.Tasks.Task<string> GuardarFrutasAsync(string[] frutas) {
            return base.Channel.GuardarFrutasAsync(frutas);
        }
        
        public Externo.ServiceReference1.Equipos[] ObtenerEquipos() {
            return base.Channel.ObtenerEquipos();
        }
        
        public System.Threading.Tasks.Task<Externo.ServiceReference1.Equipos[]> ObtenerEquiposAsync() {
            return base.Channel.ObtenerEquiposAsync();
        }
        
        public string GuardarEquipos(Externo.ServiceReference1.Equipos[] equipos) {
            return base.Channel.GuardarEquipos(equipos);
        }
        
        public System.Threading.Tasks.Task<string> GuardarEquiposAsync(Externo.ServiceReference1.Equipos[] equipos) {
            return base.Channel.GuardarEquiposAsync(equipos);
        }
        
        public string GuardarXML(string xml) {
            return base.Channel.GuardarXML(xml);
        }
        
        public System.Threading.Tasks.Task<string> GuardarXMLAsync(string xml) {
            return base.Channel.GuardarXMLAsync(xml);
        }
        
        public string RetornarJson() {
            return base.Channel.RetornarJson();
        }
        
        public System.Threading.Tasks.Task<string> RetornarJsonAsync() {
            return base.Channel.RetornarJsonAsync();
        }
        
        public string GuardarJson(string json) {
            return base.Channel.GuardarJson(json);
        }
        
        public System.Threading.Tasks.Task<string> GuardarJsonAsync(string json) {
            return base.Channel.GuardarJsonAsync(json);
        }
        
        public string ObtenerProductos() {
            return base.Channel.ObtenerProductos();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerProductosAsync() {
            return base.Channel.ObtenerProductosAsync();
        }
        
        public Externo.ServiceReference1.Producto ObtenerProducto(int idproducto) {
            return base.Channel.ObtenerProducto(idproducto);
        }
        
        public System.Threading.Tasks.Task<Externo.ServiceReference1.Producto> ObtenerProductoAsync(int idproducto) {
            return base.Channel.ObtenerProductoAsync(idproducto);
        }
        
        public string ActualizarProducto(Externo.ServiceReference1.Producto producto) {
            return base.Channel.ActualizarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarProductoAsync(Externo.ServiceReference1.Producto producto) {
            return base.Channel.ActualizarProductoAsync(producto);
        }
        
        public int GuardarProducto(Externo.ServiceReference1.Producto producto) {
            return base.Channel.GuardarProducto(producto);
        }
        
        public System.Threading.Tasks.Task<int> GuardarProductoAsync(Externo.ServiceReference1.Producto producto) {
            return base.Channel.GuardarProductoAsync(producto);
        }
        
        public string EliminarProducto(int idproducto) {
            return base.Channel.EliminarProducto(idproducto);
        }
        
        public System.Threading.Tasks.Task<string> EliminarProductoAsync(int idproducto) {
            return base.Channel.EliminarProductoAsync(idproducto);
        }
        
        public string ObtenerFecha() {
            return base.Channel.ObtenerFecha();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerFechaAsync() {
            return base.Channel.ObtenerFechaAsync();
        }
        
        public string ObtenerHora() {
            return base.Channel.ObtenerHora();
        }
        
        public System.Threading.Tasks.Task<string> ObtenerHoraAsync() {
            return base.Channel.ObtenerHoraAsync();
        }
    }
}
